CREATE TABLE IF NOT EXISTS CON_REPO (
  ID INT IDENTITY PRIMARY KEY,
  CODE VARCHAR,
  NAME VARCHAR,
  TYPE VARCHAR
);
CREATE TABLE IF NOT EXISTS CONTAINER(
  ID INT IDENTITY PRIMARY KEY,
  CON_NO VARCHAR,
  NAME VARCHAR,
  REPO_CODE VARCHAR
);